# Generated by Django 5.1.3 on 2024-11-18 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_alter_walletbalancehistory_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletbalancehistory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
