# Generated by Django 5.1.3 on 2025-04-18 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0003_country_customuser_is_subscribed_bank_rib'),
        ('transaction', '0006_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='TariffGrid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='fee',
            name='max_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='fee',
            name='min_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='fee',
            name='tariff_grid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='transaction.tariffgrid'),
        ),
        migrations.AlterUniqueTogether(
            name='fee',
            unique_together={('tariff_grid', 'transaction_type', 'min_amount', 'max_amount', 'merchant', 'bank')},
        ),
    ]
