# Generated by Django 5.1.3 on 2025-04-18 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0004_wallet_is_platform'),
        ('transaction', '0007_tariffgrid_fee_max_amount_fee_min_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='fee_applied',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='FeeDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_type', models.CharField(choices=[('provider', 'Fournisseur'), ('bank', 'Banque'), ('merchant', 'Marchand')], max_length=30)),
                ('actor_id', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='FeeDistributionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('send_money', "Envoi d'argent"), ('topup', 'Rechargement'), ('merchant_payment', 'Paiement marchand')], max_length=30)),
                ('provider_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('bank_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('merchant_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='actor.bank')),
                ('merchant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='actor.merchant')),
            ],
        ),
    ]
