# Generated by Django 5.2.2 on 2025-08-17 12:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transaction", "0008_transaction_fee_applied_feedistribution_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="order_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
