# Generated by Django 5.1.2 on 2025-09-07 17:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transaction", "0009_transaction_order_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="additional_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="fee",
            name="transaction_type",
            field=models.CharField(default="TRANSFER", max_length=30),
        ),
        migrations.AlterField(
            model_name="feedistributionrule",
            name="transaction_type",
            field=models.CharField(default="TRANSFER", max_length=30),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="status",
            field=models.CharField(default="PENDING", max_length=10),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="walletbalancehistory",
            name="transaction_type",
            field=models.CharField(max_length=50),
        ),
    ]
