# Generated by Django 5.1.2 on 2025-09-08 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transaction", "0010_transaction_additional_data_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="external_reference",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
