# Generated by Django 5.2.2 on 2025-10-31 04:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transaction", "0011_transaction_external_reference"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransactionStatusCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_id", models.CharField(db_index=True, max_length=100)),
                ("external_reference", models.CharField(max_length=200, unique=True)),
                ("status", models.CharField(max_length=50)),
                ("transaction_type", models.CharField(max_length=50)),
                ("partner", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_checked_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Transaction status check",
                "verbose_name_plural": "Transaction status checks",
            },
        ),
    ]
