# Generated by Django 5.1.3 on 2025-04-18 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0003_country_customuser_is_subscribed_bank_rib'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='is_platform',
            field=models.BooleanField(default=False),
        ),
    ]
