# Generated by Django 5.1.2 on 2025-10-31 11:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("actor", "0004_wallet_is_platform"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="uuid",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, unique=True
            ),
        ),
    ]
