# Generated by Django 5.1.2 on 2026-03-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("actor", "0005_customuser_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="fcm_token",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
